name: todo_sqlite
description: 'A new Flutter project for product management using SQLite.'
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.0.0+4   # SQLite for database management
  path: ^1.8.0        # Required for file path management for SQLite
  provider: ^6.0.5    # Optional, for state management (helpful for larger projects)
  cupertino_icons: ^1.0.8 # Optional, for iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1 # Linting rules for better coding practices

flutter:
  uses-material-design: true # Ensures Material Icons are included
